export const planets = [
  {
    category: "Giant planets",
    subcategories: [
      {
        name: "Gas giants",
        planets: ["Jupiter", "Saturn"],
      },
      {
        name: "Ice giants",
        planets: ["Uranus", "Neptune"],
      },
      {
        name: "Super giants",
        planets: ["HD 100546 b", "Kepler-10c"],
      },
    ],
  },
  {
    category: "Dwarf planets",
    subcategories: [
      {
        name: "Plutoids",
        planets: ["Pluto", "Haumea", "Makemake", "Eris"],
      },
      {
        name: "Others",
        planets: ["Ceres"],
      },
    ],
  },
];

export const studentData = [
  { id: 1, name: "John Doe", age: 20, grade: "A" },
  { id: 2, name: "Jane Smith", age: 22, grade: "B" },
  { id: 3, name: "David Johnson", age: 21, grade: "C" },
  { id: 4, name: "Emily Brown", age: 19, grade: "A" },
  { id: 5, name: "Michael Lee", age: 23, grade: "B" },
  { id: 6, name: "Sarah Jones", age: 20, grade: "A" },
  { id: 7, name: "Daniel Wilson", age: 22, grade: "C" },
  { id: 8, name: "Olivia Taylor", age: 21, grade: "B" },
  { id: 9, name: "Matthew White", age: 19, grade: "A" },
  { id: 10, name: "Sophia Martinez", age: 20, grade: "C" },
  { id: 11, name: "James Anderson", age: 21, grade: "B" },
  { id: 12, name: "Emma Thomas", age: 20, grade: "A" },
  { id: 13, name: "Liam Roberts", age: 23, grade: "C" },
  { id: 14, name: "Isabella Clark", age: 19, grade: "B" },
  { id: 15, name: "Noah Hall", age: 22, grade: "A" },
  { id: 16, name: "Mia Lewis", age: 21, grade: "C" },
  { id: 17, name: "Ethan Walker", age: 20, grade: "B" },
  { id: 18, name: "Ava Allen", age: 19, grade: "A" },
  { id: 19, name: "Lucas Young", age: 23, grade: "B" },
  { id: 20, name: "Charlotte King", age: 22, grade: "C" },
  { id: 21, name: "Benjamin Scott", age: 21, grade: "A" },
  { id: 22, name: "Amelia Green", age: 20, grade: "B" },
  { id: 23, name: "William Adams", age: 19, grade: "C" },
  { id: 24, name: "Harper Baker", age: 23, grade: "A" },
  { id: 25, name: "Elijah Gonzalez", age: 22, grade: "B" },
  { id: 26, name: "Abigail Nelson", age: 21, grade: "C" },
  { id: 27, name: "Mason Carter", age: 20, grade: "A" },
  { id: 28, name: "Evelyn Mitchell", age: 19, grade: "B" },
  { id: 29, name: "Alexander Perez", age: 23, grade: "C" },
  { id: 30, name: "Sofia Roberts", age: 22, grade: "A" },
];

export const fields = [
  { name: "Animal", subMenu: ["Tiger", "Fox", "Dog", "Cat"] },
  { name: "Sports", subMenu: ["Football", "Basketball", "Tennis", "Cricket"] },
  { name: "Cartoon", subMenu: ["Mickey Mouse", "Tom & Jerry", "SpongeBob", "Pokemon"] },
  { name: "Movie", subMenu: ["Action", "Comedy", "Drama", "Horror"] },
  { name: "Technology", subMenu: ["Programming", "AI", "Blockchain", "IoT"] },
  { name: "Food", subMenu: ["Pizza", "Burger", "Sushi", "Tacos"] },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
